apps/datasetmanager/dataset_data.py
apps/datasetmanager/fields.py
apps/metricsmanager/file_encoder.py
apps/referencepool/fixtures/references.json

A new class type 'custom' was introduced to store unknown individuals. An individual can know be passed as an ID of the reference pool or as string. 
Moreover a bug in the XLSX converter was fixed, which caused the wrong parsing of integer numbers.

Auto-Creation of Unknown Individuals

---

apps/datasetmanager/dataset_data.py
apps/datasetmanager/fields.py

When choosing a class other then custom, it was possible to save an individual as string. This wrong behavior was fixed.

Bug Fix, Individual as String is not allowed

---

config/settings.sample.py

https://github.com/policycompass/policycompass/issues/218

Fix settings.sample.py with missing comma

---

apps/datasetmanager/signals.py
apps/eventsmanager/signals.py
apps/indicatorservice/signals.py
apps/metricsmanager/signals.py
apps/visualizationsmanager/signals.py

https://github.com/policycompass/policycompass/issues/178

Fix elasticsearch to update changes

---

apps/datasetmanager/api.py

I quickly added filters by indicator for Datasets because I will need this in the frontend. Hope that is fine.

add filtering of datasets

---

apps/datasetmanager/internal_api.py
apps/metricsmanager/api.py
apps/metricsmanager/formula.py
apps/metricsmanager/serializers.py
apps/metricsmanager/urls.py
requirements.txt

- allow to compute value of a metric for given dataset
- not working yet: normalization

First draft of metrics operationalization

---

apps/datasetmanager/signals.py
apps/eventsmanager/signals.py
apps/indicatorservice/signals.py
apps/metricsmanager/signals.py
apps/visualizationsmanager/signals.py

https://github.com/policycompass/policycompass/issues/263

Fix loaddata faulty indexing

---

apps/referencepool/fixtures/references.json
apps/referencepool/models.py

This PR closes issues:
https://github.com/policycompass/policycompass/issues/236
https://github.com/policycompass/policycompass/issues/258

Policy Domain Order and CCC Open Data in External Resources

---

apps/datasetmanager/dataset_data.py
apps/datasetmanager/fields.py

This PR introduces the GET parameters individuals, time_start and time_end. Those parameters filter the dataset data respectively. 
https://github.com/policycompass/policycompass/issues/198

Filter Option for Dataset Data

---

apps/searchmanager/index_utils.py
config/settings.sample.py

Extend the indexing of objects to also include comments. Will be used to display how many comments have been given for a specific element.

Extend index comments

---

apps/metricsmanager/api.py
apps/metricsmanager/formula.ebnf
apps/metricsmanager/formula.py
apps/metricsmanager/migrations/0004_auto_20151015_0715.py
apps/metricsmanager/models.py
apps/metricsmanager/serializers.py

- check that all variables are given
- check structure of variable dict
- filter supplementary variables

Extend validation of formula and variables

---

policycompass_services/auth.py

`urllib.request.urlopen` throws an exception if return code != 200. We now only state *invalid credentials* if adhocracy returns 400 and fail hard on any other error as it would be unexpected.

Fix exception handling in wrong credentials case

---

apps/datasetmanager/dataset_data.py
apps/datasetmanager/file_encoder.py

Less entries in the log file make debugging easier.

Decrease logging verbosity

---

apps/visualizationsmanager/api.py
apps/visualizationsmanager/migrations/0005_auto_20151023_0824.py
apps/visualizationsmanager/migrations/0006_auto_20151023_1230.py
apps/visualizationsmanager/models.py
apps/visualizationsmanager/serializers.py

Rename user_id as creator_path

Rename some fields in visualisation model to add auth

---

apps/datasetmanager/dataset_data.py
apps/datasetmanager/file_encoder.py

This PR fixes this issue: https://github.com/policycompass/policycompass/issues/319

Swichted from Unix timpstamp to ISO as time base

---

apps/datasetmanager/api.py
apps/datasetmanager/migrations/0003_auto_20151028_1559.py
apps/datasetmanager/models.py
apps/datasetmanager/serializers.py
apps/indicatorservice/api.py
apps/indicatorservice/migrations/0004_indicator_creator_path.py
apps/indicatorservice/models.py
apps/indicatorservice/serializers.py
apps/metricsmanager/api.py
apps/visualizationsmanager/api.py
policycompass_services/auth.py
policycompass_services/permissions.py

This PR introduces Authentication and Authorization for the Dataset Manager and Indicator Service. Moreover it adds the object permission class.

Dataset and Indicator Auth

---

apps/visualizationsmanager/api.py
apps/visualizationsmanager/serializers.py

This PR includes auth for the visualization module.

Auth for Creation of Visualization

---

apps/datasetmanager/migrations/0002_dataframe.py

https://github.com/policycompass/policycompass/issues/364

dataset migration fails without database

---

apps/visualizationsmanager/admin.py
apps/visualizationsmanager/api.py
apps/visualizationsmanager/migrations/0007_visualization_location.py
apps/visualizationsmanager/migrations/0008_visualizationindomain.py
apps/visualizationsmanager/models.py
apps/visualizationsmanager/serializers.py
config/settings_basic.py

This PR is to add 2 new fields to the visualization model (location and policy domain)

Add location and policy domain v2

---

apps/datasetmanager/api.py
apps/datasetmanager/file_encoder.py
apps/datasetmanager/urls.py

ref policycompass/policycompass#363

Add CKAN data import

---

apps/datasetmanager/api.py

ref policycompass/policycompass#371

Added start parameter to CKANSearchProxy for pagination

---

apps/referencepool/fixtures/references.json

https://github.com/policycompass/policycompass/issues/337

Rename Some References

---

apps/datasetmanager/file_encoder.py

https://github.com/policycompass/policycompass/issues/351

Convert Zeros to String

---

README.md

This documents the coding style efforts introduced in #88. It's a part
of policycompass/policycompass#380.

Add coding style section in README

---

apps/ratingsmanager/views.py

https://github.com/policycompass/policycompass/issues/328

Auth for Rating Service

---

apps/datasetmanager/dataset_data.py

https://github.com/policycompass/policycompass/issues/384

Catch not possbile time get parameter

---

apps/indicatorservice/api.py

https://github.com/policycompass/policycompass/issues/369

Deactivate pagination for indicators by get parameter

---

apps/referencepool/models.py

https://github.com/policycompass/policycompass/issues/336

Order References By Title

---

apps/metricsmanager/api.py

This is not tested yet, @MagdaN will take care of it.

Make metrics editable

---

apps/eventsmanager/admin.py
apps/eventsmanager/migrations/0005_event_creator_path.py
apps/eventsmanager/models.py
apps/eventsmanager/serializers.py
apps/eventsmanager/views.py

This PR solves the following issue:
https://github.com/policycompass/policycompass/issues/395

event auth integration

---

apps/feedbackmanager/__init__.py
apps/feedbackmanager/admin.py
apps/feedbackmanager/apps.py
apps/feedbackmanager/migrations/0001_initial.py
apps/feedbackmanager/migrations/0002_auto_20160106_1642.py
apps/feedbackmanager/migrations/0003_feedback_link.py
apps/feedbackmanager/models.py
apps/feedbackmanager/serializers.py
apps/feedbackmanager/signals.py
apps/feedbackmanager/tests.py
apps/feedbackmanager/urls.py
apps/feedbackmanager/views.py
apps/referencepool/migrations/0007_auto_20160107_1555.py
config/settings_basic.py
policycompass_services/api.py
policycompass_services/urls.py

https://github.com/policycompass/policycompass/issues/393

Feedback Module

---

apps/eventsmanager/admin.py
apps/eventsmanager/migrations/0005_event_creator_path.py
apps/eventsmanager/models.py
apps/eventsmanager/serializers.py
apps/eventsmanager/views.py
apps/feedbackmanager/__init__.py
apps/feedbackmanager/admin.py
apps/feedbackmanager/apps.py
apps/feedbackmanager/migrations/0001_initial.py
apps/feedbackmanager/migrations/0002_auto_20160106_1642.py
apps/feedbackmanager/models.py
apps/feedbackmanager/serializers.py
apps/feedbackmanager/signals.py
apps/feedbackmanager/tests.py
apps/feedbackmanager/urls.py
apps/feedbackmanager/views.py
config/settings_basic.py
policycompass_services/api.py
policycompass_services/urls.py

created feedback service backend
https://github.com/policycompass/policycompass/issues/393

created feedback service backend

---

apps/datasetmanager/dataset_data.py

https://github.com/policycompass/policycompass/issues/441

Bug Fix Individual Detection

---

apps/eventsmanager/serializers.py
apps/eventsmanager/views.py

policycompass/policycompass#450
policycompass/policycompass#451

Event policy domains

---

apps/ratingsmanager/views.py

https://github.com/policycompass/policycompass/issues/446

Disabled 404 for ratings

---

apps/indicatorservice/fixtures/indicators.json
apps/indicatorservice/migrations/0006_remove_indicator_acronym.py
apps/indicatorservice/models.py

https://github.com/policycompass/policycompass/issues/464

Removed Acronym from Indicator Service

---

apps/datasetmanager/api.py
apps/datasetmanager/signals.py
apps/datasetmanager/urls.py
requirements.txt

https://github.com/policycompass/policycompass/issues/467
https://github.com/policycompass/policycompass/issues/385

Eurostat Import backend

---

apps/visualizationsmanager/migrations/0009_auto_20160519_1333.py
apps/visualizationsmanager/models.py

PR related wit issue policycompass/policycompass/issues/538
This PR adds 2 new fiels into the visualisation model.

add custom scale

---

apps/datasetmanager/internal_api.py
apps/metricsmanager/models.py
apps/metricsmanager/signals.py

goes together with this one: https://github.com/policycompass/policycompass-frontend/pull/460
@FabiApfelkern: I don't know if this is the best solution for it. Do you have better ideas?

add post_delete signal to metric

---

apps/visualizationsmanager/migrations/0010_visualization_is_draft.py
apps/visualizationsmanager/models.py

This PR is to add the field "is_draft" to the visualisation model.
Related with issue 618 (policycompass/policycompass/issues/618 )

add draft field to the visualisation model

---

apps/datasetmanager/fields.py

https://github.com/policycompass/policycompass/issues/629

HTTP 404 instead of 500, if dataset doesn't exist

---

apps/visualizationsmanager/migrations/0011_visualization_derived_from_id.py
apps/visualizationsmanager/models.py

PR related with issue # 604 (policycompass/policycompass/issues/604)
Adds field "derived_from_id" to the visualisation BE

add derived_from_id when save a visualisation copy

---

apps/datasetmanager/api.py
apps/eventsmanager/views.py

https://github.com/policycompass/policycompass/issues/482
https://github.com/policycompass/policycompass/issues/483

added deletion logic for datasets and events

---

apps/referencepool/api.py

The search function will now check the first and last characters.
For example: "api/v1/references/individuals?q=westgermany" will return "Western Sussex" and "Germany"

improved the search function for individuals

---

apps/datasetmanager/migrations/0010_dataset_is_draft.py
apps/datasetmanager/models.py
apps/eventsmanager/migrations/0012_event_is_draft.py
apps/eventsmanager/models.py
apps/metricsmanager/migrations/0006_metric_is_draft.py
apps/metricsmanager/models.py

https://github.com/policycompass/policycompass/issues/618

added is_draft to dataset, event and metric models

---

apps/indicatorservice/admin.py
apps/indicatorservice/migrations/0007_auto_20160912_1156.py
apps/indicatorservice/models.py
apps/indicatorservice/serializers.py

https://github.com/policycompass/policycompass/issues/472

Indicator rework

---

apps/datasetmanager/api.py

https://github.com/policycompass/policycompass/issues/661

removed auth from edp request

---

apps/eventsmanager/extractors/Wikipedia/__init__.py
config/settings.sample.py

Not to merge yet.
Requires EventMiner flask server running on http://localhost:5000/extraction

added the wikipedia extractor

---

apps/searchmanager/index_utils.py
apps/storymanager/api.py

https://github.com/policycompass/policycompass/issues/685

storymanager: updated the storymanager api and corrected searchmanager for stories

---

apps/datasetmanager/migrations/0012_dataset_derived_from_id.py
apps/datasetmanager/models.py
apps/eventsmanager/extractors/Wikipedia/__init__.py
apps/eventsmanager/migrations/0015_event_derived_from_id.py
apps/eventsmanager/models.py
apps/storymanager/api.py
apps/storymanager/migrations/0003_story_derived_from_id.py
apps/storymanager/models.py

https://github.com/policycompass/policycompass/issues/604

added derived_from_id to datasets, events and stories

---

apps/storymanager/api.py

Storymanager api corrections
